[[Qemu]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "a011fc98a4df6094fd8742ff854419f2ca680d5c"
libc = "glibc"
os = "linux"

    [[Qemu.download]]
    sha256 = "1a06df685f54f84e30bbc9555118127d5fd2206b5187b70157142bc89cdee9b3"
    url = "https://github.com/JuliaBinaryWrappers/Qemu_jll.jl/releases/download/Qemu-v7.1.0+0/Qemu.v7.1.0.i686-linux-gnu-cxx03.tar.gz"
[[Qemu]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "57aaccd22bbd267669bb3f689d109f69fcfc2e6a"
libc = "glibc"
os = "linux"

    [[Qemu.download]]
    sha256 = "4ae551134414c0453941e0423e3b76e7ce0181bf78e89f77023f5d929f54faaa"
    url = "https://github.com/JuliaBinaryWrappers/Qemu_jll.jl/releases/download/Qemu-v7.1.0+0/Qemu.v7.1.0.i686-linux-gnu-cxx11.tar.gz"
[[Qemu]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "cce632fcca3db2bc7ffb5159a7b59870e0b36c41"
libc = "glibc"
os = "linux"

    [[Qemu.download]]
    sha256 = "8d6cc7f0b9532c2cd160f245c22c7d00488a419b52ed8b9fce8d4053da0d63ae"
    url = "https://github.com/JuliaBinaryWrappers/Qemu_jll.jl/releases/download/Qemu-v7.1.0+0/Qemu.v7.1.0.x86_64-linux-gnu-cxx03.tar.gz"
[[Qemu]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "a0dcc958dbeafd1a7432abef8b6bb5af0f72675d"
libc = "glibc"
os = "linux"

    [[Qemu.download]]
    sha256 = "37e5ccbb5df61070f6153ca8efb8968805dbd9f5059ea279397cc0337089e32e"
    url = "https://github.com/JuliaBinaryWrappers/Qemu_jll.jl/releases/download/Qemu-v7.1.0+0/Qemu.v7.1.0.x86_64-linux-gnu-cxx11.tar.gz"
[[Qemu]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "23814b9ad32d3cf4ca97cfb94c4554cd66783601"
libc = "musl"
os = "linux"

    [[Qemu.download]]
    sha256 = "be5bfc83bffe182112598d2801771c64436614311f02e294efd88afc9f5bf21b"
    url = "https://github.com/JuliaBinaryWrappers/Qemu_jll.jl/releases/download/Qemu-v7.1.0+0/Qemu.v7.1.0.x86_64-linux-musl-cxx03.tar.gz"
[[Qemu]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "735179b5dca27f32aa15c05724b81c0058c6875d"
libc = "musl"
os = "linux"

    [[Qemu.download]]
    sha256 = "a8e197ef548446d86e442823b1ec953f986864e5d8a0c2f951ff855eb3088745"
    url = "https://github.com/JuliaBinaryWrappers/Qemu_jll.jl/releases/download/Qemu-v7.1.0+0/Qemu.v7.1.0.x86_64-linux-musl-cxx11.tar.gz"
