# Autogenerated wrapper script for Qemu_jll for x86_64-linux-musl-cxx11
export qemu_aarch64, qemu_aarch64_be, qemu_alpha, qemu_arm, qemu_armeb, qemu_cris, qemu_edid, qemu_ga, qemu_hexagon, qemu_hppa, qemu_i386, qemu_img, qemu_io, qemu_m68k, qemu_microblaze, qemu_microblazeel, qemu_mips, qemu_mips64, qemu_mips64el, qemu_mipsel, qemu_mipsn32, qemu_mipsn32el, qemu_nbd, qemu_nios2, qemu_or1k, qemu_ppc, qemu_ppc64, qemu_ppc64le, qemu_riscv32, qemu_riscv64, qemu_s390x, qemu_sh4, qemu_sh4eb, qemu_sparc, qemu_sparc32plus, qemu_sparc64, qemu_system_aarch64, qemu_system_alpha, qemu_system_arm, qemu_system_avr, qemu_system_cris, qemu_system_hppa, qemu_system_i386, qemu_system_m68k, qemu_system_microblaze, qemu_system_microblazeel, qemu_system_mips, qemu_system_mips64, qemu_system_mips64el, qemu_system_mipsel, qemu_system_nios2, qemu_system_or1k, qemu_system_ppc, qemu_system_ppc64, qemu_system_riscv32, qemu_system_riscv64, qemu_system_rx, qemu_system_s390x, qemu_system_sh4, qemu_system_sh4eb, qemu_system_sparc, qemu_system_sparc64, qemu_system_tricore, qemu_system_x86_64, qemu_system_xtensa, qemu_system_xtensaeb, qemu_x86_64, qemu_xtensa, qemu_xtensaeb

using Pixman_jll
using Glib_jll
using PCRE_jll
using libcap_jll
JLLWrappers.@generate_wrapper_header("Qemu")
JLLWrappers.@declare_executable_product(qemu_aarch64)
JLLWrappers.@declare_executable_product(qemu_aarch64_be)
JLLWrappers.@declare_executable_product(qemu_alpha)
JLLWrappers.@declare_executable_product(qemu_arm)
JLLWrappers.@declare_executable_product(qemu_armeb)
JLLWrappers.@declare_executable_product(qemu_cris)
JLLWrappers.@declare_executable_product(qemu_edid)
JLLWrappers.@declare_executable_product(qemu_ga)
JLLWrappers.@declare_executable_product(qemu_hexagon)
JLLWrappers.@declare_executable_product(qemu_hppa)
JLLWrappers.@declare_executable_product(qemu_i386)
JLLWrappers.@declare_executable_product(qemu_img)
JLLWrappers.@declare_executable_product(qemu_io)
JLLWrappers.@declare_executable_product(qemu_m68k)
JLLWrappers.@declare_executable_product(qemu_microblaze)
JLLWrappers.@declare_executable_product(qemu_microblazeel)
JLLWrappers.@declare_executable_product(qemu_mips)
JLLWrappers.@declare_executable_product(qemu_mips64)
JLLWrappers.@declare_executable_product(qemu_mips64el)
JLLWrappers.@declare_executable_product(qemu_mipsel)
JLLWrappers.@declare_executable_product(qemu_mipsn32)
JLLWrappers.@declare_executable_product(qemu_mipsn32el)
JLLWrappers.@declare_executable_product(qemu_nbd)
JLLWrappers.@declare_executable_product(qemu_nios2)
JLLWrappers.@declare_executable_product(qemu_or1k)
JLLWrappers.@declare_executable_product(qemu_ppc)
JLLWrappers.@declare_executable_product(qemu_ppc64)
JLLWrappers.@declare_executable_product(qemu_ppc64le)
JLLWrappers.@declare_executable_product(qemu_riscv32)
JLLWrappers.@declare_executable_product(qemu_riscv64)
JLLWrappers.@declare_executable_product(qemu_s390x)
JLLWrappers.@declare_executable_product(qemu_sh4)
JLLWrappers.@declare_executable_product(qemu_sh4eb)
JLLWrappers.@declare_executable_product(qemu_sparc)
JLLWrappers.@declare_executable_product(qemu_sparc32plus)
JLLWrappers.@declare_executable_product(qemu_sparc64)
JLLWrappers.@declare_executable_product(qemu_system_aarch64)
JLLWrappers.@declare_executable_product(qemu_system_alpha)
JLLWrappers.@declare_executable_product(qemu_system_arm)
JLLWrappers.@declare_executable_product(qemu_system_avr)
JLLWrappers.@declare_executable_product(qemu_system_cris)
JLLWrappers.@declare_executable_product(qemu_system_hppa)
JLLWrappers.@declare_executable_product(qemu_system_i386)
JLLWrappers.@declare_executable_product(qemu_system_m68k)
JLLWrappers.@declare_executable_product(qemu_system_microblaze)
JLLWrappers.@declare_executable_product(qemu_system_microblazeel)
JLLWrappers.@declare_executable_product(qemu_system_mips)
JLLWrappers.@declare_executable_product(qemu_system_mips64)
JLLWrappers.@declare_executable_product(qemu_system_mips64el)
JLLWrappers.@declare_executable_product(qemu_system_mipsel)
JLLWrappers.@declare_executable_product(qemu_system_nios2)
JLLWrappers.@declare_executable_product(qemu_system_or1k)
JLLWrappers.@declare_executable_product(qemu_system_ppc)
JLLWrappers.@declare_executable_product(qemu_system_ppc64)
JLLWrappers.@declare_executable_product(qemu_system_riscv32)
JLLWrappers.@declare_executable_product(qemu_system_riscv64)
JLLWrappers.@declare_executable_product(qemu_system_rx)
JLLWrappers.@declare_executable_product(qemu_system_s390x)
JLLWrappers.@declare_executable_product(qemu_system_sh4)
JLLWrappers.@declare_executable_product(qemu_system_sh4eb)
JLLWrappers.@declare_executable_product(qemu_system_sparc)
JLLWrappers.@declare_executable_product(qemu_system_sparc64)
JLLWrappers.@declare_executable_product(qemu_system_tricore)
JLLWrappers.@declare_executable_product(qemu_system_x86_64)
JLLWrappers.@declare_executable_product(qemu_system_xtensa)
JLLWrappers.@declare_executable_product(qemu_system_xtensaeb)
JLLWrappers.@declare_executable_product(qemu_x86_64)
JLLWrappers.@declare_executable_product(qemu_xtensa)
JLLWrappers.@declare_executable_product(qemu_xtensaeb)
function __init__()
    JLLWrappers.@generate_init_header(Pixman_jll, Glib_jll, PCRE_jll, libcap_jll)
    JLLWrappers.@init_executable_product(
        qemu_aarch64,
        "bin/qemu-aarch64",
    )

    JLLWrappers.@init_executable_product(
        qemu_aarch64_be,
        "bin/qemu-aarch64_be",
    )

    JLLWrappers.@init_executable_product(
        qemu_alpha,
        "bin/qemu-alpha",
    )

    JLLWrappers.@init_executable_product(
        qemu_arm,
        "bin/qemu-arm",
    )

    JLLWrappers.@init_executable_product(
        qemu_armeb,
        "bin/qemu-armeb",
    )

    JLLWrappers.@init_executable_product(
        qemu_cris,
        "bin/qemu-cris",
    )

    JLLWrappers.@init_executable_product(
        qemu_edid,
        "bin/qemu-edid",
    )

    JLLWrappers.@init_executable_product(
        qemu_ga,
        "bin/qemu-ga",
    )

    JLLWrappers.@init_executable_product(
        qemu_hexagon,
        "bin/qemu-hexagon",
    )

    JLLWrappers.@init_executable_product(
        qemu_hppa,
        "bin/qemu-hppa",
    )

    JLLWrappers.@init_executable_product(
        qemu_i386,
        "bin/qemu-i386",
    )

    JLLWrappers.@init_executable_product(
        qemu_img,
        "bin/qemu-img",
    )

    JLLWrappers.@init_executable_product(
        qemu_io,
        "bin/qemu-io",
    )

    JLLWrappers.@init_executable_product(
        qemu_m68k,
        "bin/qemu-m68k",
    )

    JLLWrappers.@init_executable_product(
        qemu_microblaze,
        "bin/qemu-microblaze",
    )

    JLLWrappers.@init_executable_product(
        qemu_microblazeel,
        "bin/qemu-microblazeel",
    )

    JLLWrappers.@init_executable_product(
        qemu_mips,
        "bin/qemu-mips",
    )

    JLLWrappers.@init_executable_product(
        qemu_mips64,
        "bin/qemu-mips64",
    )

    JLLWrappers.@init_executable_product(
        qemu_mips64el,
        "bin/qemu-mips64el",
    )

    JLLWrappers.@init_executable_product(
        qemu_mipsel,
        "bin/qemu-mipsel",
    )

    JLLWrappers.@init_executable_product(
        qemu_mipsn32,
        "bin/qemu-mipsn32",
    )

    JLLWrappers.@init_executable_product(
        qemu_mipsn32el,
        "bin/qemu-mipsn32el",
    )

    JLLWrappers.@init_executable_product(
        qemu_nbd,
        "bin/qemu-nbd",
    )

    JLLWrappers.@init_executable_product(
        qemu_nios2,
        "bin/qemu-nios2",
    )

    JLLWrappers.@init_executable_product(
        qemu_or1k,
        "bin/qemu-or1k",
    )

    JLLWrappers.@init_executable_product(
        qemu_ppc,
        "bin/qemu-ppc",
    )

    JLLWrappers.@init_executable_product(
        qemu_ppc64,
        "bin/qemu-ppc64",
    )

    JLLWrappers.@init_executable_product(
        qemu_ppc64le,
        "bin/qemu-ppc64le",
    )

    JLLWrappers.@init_executable_product(
        qemu_riscv32,
        "bin/qemu-riscv32",
    )

    JLLWrappers.@init_executable_product(
        qemu_riscv64,
        "bin/qemu-riscv64",
    )

    JLLWrappers.@init_executable_product(
        qemu_s390x,
        "bin/qemu-s390x",
    )

    JLLWrappers.@init_executable_product(
        qemu_sh4,
        "bin/qemu-sh4",
    )

    JLLWrappers.@init_executable_product(
        qemu_sh4eb,
        "bin/qemu-sh4eb",
    )

    JLLWrappers.@init_executable_product(
        qemu_sparc,
        "bin/qemu-sparc",
    )

    JLLWrappers.@init_executable_product(
        qemu_sparc32plus,
        "bin/qemu-sparc32plus",
    )

    JLLWrappers.@init_executable_product(
        qemu_sparc64,
        "bin/qemu-sparc64",
    )

    JLLWrappers.@init_executable_product(
        qemu_system_aarch64,
        "bin/qemu-system-aarch64",
    )

    JLLWrappers.@init_executable_product(
        qemu_system_alpha,
        "bin/qemu-system-alpha",
    )

    JLLWrappers.@init_executable_product(
        qemu_system_arm,
        "bin/qemu-system-arm",
    )

    JLLWrappers.@init_executable_product(
        qemu_system_avr,
        "bin/qemu-system-avr",
    )

    JLLWrappers.@init_executable_product(
        qemu_system_cris,
        "bin/qemu-system-cris",
    )

    JLLWrappers.@init_executable_product(
        qemu_system_hppa,
        "bin/qemu-system-hppa",
    )

    JLLWrappers.@init_executable_product(
        qemu_system_i386,
        "bin/qemu-system-i386",
    )

    JLLWrappers.@init_executable_product(
        qemu_system_m68k,
        "bin/qemu-system-m68k",
    )

    JLLWrappers.@init_executable_product(
        qemu_system_microblaze,
        "bin/qemu-system-microblaze",
    )

    JLLWrappers.@init_executable_product(
        qemu_system_microblazeel,
        "bin/qemu-system-microblazeel",
    )

    JLLWrappers.@init_executable_product(
        qemu_system_mips,
        "bin/qemu-system-mips",
    )

    JLLWrappers.@init_executable_product(
        qemu_system_mips64,
        "bin/qemu-system-mips64",
    )

    JLLWrappers.@init_executable_product(
        qemu_system_mips64el,
        "bin/qemu-system-mips64el",
    )

    JLLWrappers.@init_executable_product(
        qemu_system_mipsel,
        "bin/qemu-system-mipsel",
    )

    JLLWrappers.@init_executable_product(
        qemu_system_nios2,
        "bin/qemu-system-nios2",
    )

    JLLWrappers.@init_executable_product(
        qemu_system_or1k,
        "bin/qemu-system-or1k",
    )

    JLLWrappers.@init_executable_product(
        qemu_system_ppc,
        "bin/qemu-system-ppc",
    )

    JLLWrappers.@init_executable_product(
        qemu_system_ppc64,
        "bin/qemu-system-ppc64",
    )

    JLLWrappers.@init_executable_product(
        qemu_system_riscv32,
        "bin/qemu-system-riscv32",
    )

    JLLWrappers.@init_executable_product(
        qemu_system_riscv64,
        "bin/qemu-system-riscv64",
    )

    JLLWrappers.@init_executable_product(
        qemu_system_rx,
        "bin/qemu-system-rx",
    )

    JLLWrappers.@init_executable_product(
        qemu_system_s390x,
        "bin/qemu-system-s390x",
    )

    JLLWrappers.@init_executable_product(
        qemu_system_sh4,
        "bin/qemu-system-sh4",
    )

    JLLWrappers.@init_executable_product(
        qemu_system_sh4eb,
        "bin/qemu-system-sh4eb",
    )

    JLLWrappers.@init_executable_product(
        qemu_system_sparc,
        "bin/qemu-system-sparc",
    )

    JLLWrappers.@init_executable_product(
        qemu_system_sparc64,
        "bin/qemu-system-sparc64",
    )

    JLLWrappers.@init_executable_product(
        qemu_system_tricore,
        "bin/qemu-system-tricore",
    )

    JLLWrappers.@init_executable_product(
        qemu_system_x86_64,
        "bin/qemu-system-x86_64",
    )

    JLLWrappers.@init_executable_product(
        qemu_system_xtensa,
        "bin/qemu-system-xtensa",
    )

    JLLWrappers.@init_executable_product(
        qemu_system_xtensaeb,
        "bin/qemu-system-xtensaeb",
    )

    JLLWrappers.@init_executable_product(
        qemu_x86_64,
        "bin/qemu-x86_64",
    )

    JLLWrappers.@init_executable_product(
        qemu_xtensa,
        "bin/qemu-xtensa",
    )

    JLLWrappers.@init_executable_product(
        qemu_xtensaeb,
        "bin/qemu-xtensaeb",
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
