# Autogenerated wrapper script for Qemu_jll for x86_64-linux-musl-cxx03
export qemu_system_aarch64, qemu_system_alpha, qemu_system_arm, qemu_system_avr, qemu_system_cris, qemu_system_hppa, qemu_system_i386, qemu_system_m68k, qemu_system_microblaze, qemu_system_microblazeel, qemu_system_mips, qemu_system_mips64, qemu_system_mips64el, qemu_system_mipsel, qemu_system_nios2, qemu_system_or1k, qemu_system_ppc, qemu_system_ppc64, qemu_system_riscv32, qemu_system_riscv64, qemu_system_rx, qemu_system_s390x, qemu_system_sh4, qemu_system_sh4eb, qemu_system_sparc, qemu_system_sparc64, qemu_system_tricore, qemu_system_x86_64, qemu_system_xtensa, qemu_system_xtensaeb

using Pixman_jll
using Glib_jll
using PCRE_jll
using libcap_jll
JLLWrappers.@generate_wrapper_header("Qemu")
JLLWrappers.@declare_executable_product(qemu_system_aarch64)
JLLWrappers.@declare_executable_product(qemu_system_alpha)
JLLWrappers.@declare_executable_product(qemu_system_arm)
JLLWrappers.@declare_executable_product(qemu_system_avr)
JLLWrappers.@declare_executable_product(qemu_system_cris)
JLLWrappers.@declare_executable_product(qemu_system_hppa)
JLLWrappers.@declare_executable_product(qemu_system_i386)
JLLWrappers.@declare_executable_product(qemu_system_m68k)
JLLWrappers.@declare_executable_product(qemu_system_microblaze)
JLLWrappers.@declare_executable_product(qemu_system_microblazeel)
JLLWrappers.@declare_executable_product(qemu_system_mips)
JLLWrappers.@declare_executable_product(qemu_system_mips64)
JLLWrappers.@declare_executable_product(qemu_system_mips64el)
JLLWrappers.@declare_executable_product(qemu_system_mipsel)
JLLWrappers.@declare_executable_product(qemu_system_nios2)
JLLWrappers.@declare_executable_product(qemu_system_or1k)
JLLWrappers.@declare_executable_product(qemu_system_ppc)
JLLWrappers.@declare_executable_product(qemu_system_ppc64)
JLLWrappers.@declare_executable_product(qemu_system_riscv32)
JLLWrappers.@declare_executable_product(qemu_system_riscv64)
JLLWrappers.@declare_executable_product(qemu_system_rx)
JLLWrappers.@declare_executable_product(qemu_system_s390x)
JLLWrappers.@declare_executable_product(qemu_system_sh4)
JLLWrappers.@declare_executable_product(qemu_system_sh4eb)
JLLWrappers.@declare_executable_product(qemu_system_sparc)
JLLWrappers.@declare_executable_product(qemu_system_sparc64)
JLLWrappers.@declare_executable_product(qemu_system_tricore)
JLLWrappers.@declare_executable_product(qemu_system_x86_64)
JLLWrappers.@declare_executable_product(qemu_system_xtensa)
JLLWrappers.@declare_executable_product(qemu_system_xtensaeb)
function __init__()
    JLLWrappers.@generate_init_header(Pixman_jll, Glib_jll, PCRE_jll, libcap_jll)
    JLLWrappers.@init_executable_product(
        qemu_system_aarch64,
        "bin/qemu-system-aarch64",
    )

    JLLWrappers.@init_executable_product(
        qemu_system_alpha,
        "bin/qemu-system-alpha",
    )

    JLLWrappers.@init_executable_product(
        qemu_system_arm,
        "bin/qemu-system-arm",
    )

    JLLWrappers.@init_executable_product(
        qemu_system_avr,
        "bin/qemu-system-avr",
    )

    JLLWrappers.@init_executable_product(
        qemu_system_cris,
        "bin/qemu-system-cris",
    )

    JLLWrappers.@init_executable_product(
        qemu_system_hppa,
        "bin/qemu-system-hppa",
    )

    JLLWrappers.@init_executable_product(
        qemu_system_i386,
        "bin/qemu-system-i386",
    )

    JLLWrappers.@init_executable_product(
        qemu_system_m68k,
        "bin/qemu-system-m68k",
    )

    JLLWrappers.@init_executable_product(
        qemu_system_microblaze,
        "bin/qemu-system-microblaze",
    )

    JLLWrappers.@init_executable_product(
        qemu_system_microblazeel,
        "bin/qemu-system-microblazeel",
    )

    JLLWrappers.@init_executable_product(
        qemu_system_mips,
        "bin/qemu-system-mips",
    )

    JLLWrappers.@init_executable_product(
        qemu_system_mips64,
        "bin/qemu-system-mips64",
    )

    JLLWrappers.@init_executable_product(
        qemu_system_mips64el,
        "bin/qemu-system-mips64el",
    )

    JLLWrappers.@init_executable_product(
        qemu_system_mipsel,
        "bin/qemu-system-mipsel",
    )

    JLLWrappers.@init_executable_product(
        qemu_system_nios2,
        "bin/qemu-system-nios2",
    )

    JLLWrappers.@init_executable_product(
        qemu_system_or1k,
        "bin/qemu-system-or1k",
    )

    JLLWrappers.@init_executable_product(
        qemu_system_ppc,
        "bin/qemu-system-ppc",
    )

    JLLWrappers.@init_executable_product(
        qemu_system_ppc64,
        "bin/qemu-system-ppc64",
    )

    JLLWrappers.@init_executable_product(
        qemu_system_riscv32,
        "bin/qemu-system-riscv32",
    )

    JLLWrappers.@init_executable_product(
        qemu_system_riscv64,
        "bin/qemu-system-riscv64",
    )

    JLLWrappers.@init_executable_product(
        qemu_system_rx,
        "bin/qemu-system-rx",
    )

    JLLWrappers.@init_executable_product(
        qemu_system_s390x,
        "bin/qemu-system-s390x",
    )

    JLLWrappers.@init_executable_product(
        qemu_system_sh4,
        "bin/qemu-system-sh4",
    )

    JLLWrappers.@init_executable_product(
        qemu_system_sh4eb,
        "bin/qemu-system-sh4eb",
    )

    JLLWrappers.@init_executable_product(
        qemu_system_sparc,
        "bin/qemu-system-sparc",
    )

    JLLWrappers.@init_executable_product(
        qemu_system_sparc64,
        "bin/qemu-system-sparc64",
    )

    JLLWrappers.@init_executable_product(
        qemu_system_tricore,
        "bin/qemu-system-tricore",
    )

    JLLWrappers.@init_executable_product(
        qemu_system_x86_64,
        "bin/qemu-system-x86_64",
    )

    JLLWrappers.@init_executable_product(
        qemu_system_xtensa,
        "bin/qemu-system-xtensa",
    )

    JLLWrappers.@init_executable_product(
        qemu_system_xtensaeb,
        "bin/qemu-system-xtensaeb",
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
